// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "ui.h"

Fl_Menu_Item AFSToolsUI::menu_mode_sel[] = {
 {"\320\240\320\260\321\201\320\277\320\260\320\272\320\276\320\262\320\260\321\
\202\321\214", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"\320\243\320\277\320\260\320\272\320\276\320\262\320\260\321\202\321\214", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* AFSToolsUI::btn_unpack = AFSToolsUI::menu_mode_sel + 0;
Fl_Menu_Item* AFSToolsUI::btn_pack = AFSToolsUI::menu_mode_sel + 1;

AFSToolsUI::AFSToolsUI() {
  { m_window = new Fl_Double_Window(305, 640, "AFS Tools");
    m_window->box(FL_GLEAM_ROUND_DOWN_BOX);
    m_window->color((Fl_Color)156);
    m_window->selection_color(FL_DARK1);
    m_window->user_data((void*)(this));
    { mode_sel = new Fl_Choice(20, 40, 135, 25, "\320\222\321\213\320\261\320\276\321\200 \321\200\320\265\320\266\320\270\
\320\274\320\260:");
      mode_sel->box(FL_NO_BOX);
      mode_sel->down_box(FL_BORDER_BOX);
      mode_sel->color((Fl_Color)206);
      mode_sel->labeltype(FL_ENGRAVED_LABEL);
      mode_sel->labelsize(16);
      mode_sel->align(Fl_Align(FL_ALIGN_TOP));
      mode_sel->menu(menu_mode_sel);
    } // Fl_Choice* mode_sel
    { fbrowser1 = new Fl_File_Browser(20, 120, 265, 460);
      fbrowser1->type(2);
      fbrowser1->box(FL_GLEAM_ROUND_DOWN_BOX);
      fbrowser1->color(FL_LIGHT2);
      fbrowser1->when(FL_WHEN_CHANGED);
    } // Fl_File_Browser* fbrowser1
    { btn_all_files = new Fl_Light_Button(20, 80, 115, 25, "\320\222\321\201\321\221 \320\262 \320\277\320\260\320\277\320\272\320\265");
      btn_all_files->box(FL_GLEAM_UP_BOX);
      btn_all_files->down_box(FL_GLEAM_ROUND_DOWN_BOX);
      btn_all_files->color((Fl_Color)206);
      btn_all_files->selection_color(FL_GREEN);
      btn_all_files->when(FL_WHEN_RELEASE_ALWAYS);
    } // Fl_Light_Button* btn_all_files
    { Fl_Group* o = new Fl_Group(160, 10, 120, 100, "\320\241\320\277\320\270\321\201\320\276\320\272 \320\270\320\274\321\221\
\320\275");
      o->box(FL_GTK_DOWN_BOX);
      o->color((Fl_Color)156);
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelsize(16);
      o->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
      { rb_ff = new Fl_Round_Button(170, 40, 100, 20, "\320\270\320\267 \321\204\320\260\320\271\320\273\320\260");
        rb_ff->type(102);
        rb_ff->down_box(FL_ROUND_DOWN_BOX);
        rb_ff->value(1);
      } // Fl_Round_Button* rb_ff
      { rb_fl = new Fl_Round_Button(170, 60, 100, 20, "\320\270\320\267 *.lst");
        rb_fl->type(102);
        rb_fl->down_box(FL_ROUND_DOWN_BOX);
        rb_fl->when(FL_WHEN_RELEASE_ALWAYS);
      } // Fl_Round_Button* rb_fl
      { rb_nn = new Fl_Round_Button(170, 80, 100, 20, "\320\261\320\265\320\267 \320\270\320\274\321\221\320\275");
        rb_nn->type(102);
        rb_nn->down_box(FL_ROUND_DOWN_BOX);
      } // Fl_Round_Button* rb_nn
      o->end();
    } // Fl_Group* o
    { run_btn = new Fl_Button(80, 590, 135, 30, "\320\240\320\260\321\201\320\277\320\260\320\272\320\276\320\262\320\260\321\
\202\321\214");
      run_btn->box(FL_GLEAM_ROUND_UP_BOX);
      run_btn->down_box(FL_GLEAM_ROUND_DOWN_BOX);
      run_btn->color((Fl_Color)206);
      run_btn->labeltype(FL_EMBOSSED_LABEL);
      run_btn->labelsize(18);
      run_btn->deactivate();
    } // Fl_Button* run_btn
    m_window->end();
  } // Fl_Double_Window* m_window
}

OF_Choiser::OF_Choiser(Fl_Double_Window *hwnd, const char* path, const char* filter) {
  { m_win = new Fl_Double_Window(310, 540);
    m_win->box(FL_GLEAM_ROUND_DOWN_BOX);
    m_win->color((Fl_Color)156);
    m_win->user_data((void*)(this));
    { fb = new Fl_File_Browser(5, 5, 300, 485);
      fb->type(2);
      fb->box(FL_GLEAM_ROUND_DOWN_BOX);
      fb->color(FL_LIGHT2);
      fb->callback((Fl_Callback*)cb_fb, (void*)(this));
      fb->when(FL_WHEN_CHANGED);
    } // Fl_File_Browser* fb
    { sel_btn = new Fl_Return_Button(20, 495, 115, 25, "\320\223\320\276\321\202\320\276\320\262\320\276");
      sel_btn->box(FL_GLEAM_ROUND_UP_BOX);
      sel_btn->color((Fl_Color)206);
      sel_btn->labeltype(FL_ENGRAVED_LABEL);
      sel_btn->labelsize(18);
      sel_btn->callback((Fl_Callback*)cb_select_btn, (void*)(this));
      sel_btn->deactivate();
    } // Fl_Return_Button* sel_btn
    { Fl_Button* o = new Fl_Button(170, 495, 115, 25, "\320\236\321\202\320\274\320\265\320\275\320\260");
      o->box(FL_GLEAM_ROUND_UP_BOX);
      o->color((Fl_Color)206);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(18);
      o->callback((Fl_Callback*)cb_cancel_btn, (void*)(this));
    } // Fl_Button* o
    m_win->clear_border();
    m_win->end();
  } // Fl_Double_Window* m_win
  parent_win = hwnd;
  fb->filetype(Fl_File_Browser::FILES);
  fb->filter(filter);
  fb->load(path);
}

void OF_Choiser::show() {
  parent_win->hide();
  m_win->show();
  filename = NULL;
}

int OF_Choiser::visible() {
  return m_win->visible();
}

char* OF_Choiser::value() {
  return filename;
}

void cb_cancel_btn(Fl_Button* b, void* d) {
  fc->filename = NULL;
  fc->parent_win->show();
  fc->m_win->hide();
}

void cb_select_btn(Fl_Return_Button* b, void* d) {
  fc->parent_win->show();
  fc->m_win->hide();
}

void cb_fb(Fl_File_Browser *fb, void* userdata) {
  int i, ln = fb->size();
  	
  	for (i = 0; i <= ln; i++)
  	{
  		if (fb->selected(i))
  			break;
  	}
  	
  	if (i > ln)
  	{
  		fc->sel_btn->deactivate();
  		fc->filename = NULL;
  		return;
  	}
  	
  	printf("%s\n", fb->text(i));
  	fc->sel_btn->activate();
  	fc->filename = (char *) fb->text(i);
}

Progress_Bar::Progress_Bar(Fl_Double_Window *hwnd) {
  { m_win = new Fl_Window(500, 115);
    m_win->box(FL_GLEAM_ROUND_DOWN_BOX);
    m_win->color((Fl_Color)156);
    m_win->user_data((void*)(this));
    { w_pbar1 = new Fl_Progress(15, 15, 470, 35, "0/0");
      w_pbar1->box(FL_GLEAM_ROUND_DOWN_BOX);
      w_pbar1->color((Fl_Color)212);
      w_pbar1->selection_color(FL_GREEN);
      w_pbar1->labeltype(FL_EMBOSSED_LABEL);
      w_pbar1->labelfont(10);
      w_pbar1->labelsize(24);
    } // Fl_Progress* w_pbar1
    { w_pbar2 = new Fl_Progress(15, 66, 470, 35, "0%");
      w_pbar2->box(FL_GLEAM_ROUND_DOWN_BOX);
      w_pbar2->color((Fl_Color)212);
      w_pbar2->selection_color(FL_GREEN);
      w_pbar2->labeltype(FL_EMBOSSED_LABEL);
      w_pbar2->labelfont(10);
      w_pbar2->labelsize(24);
    } // Fl_Progress* w_pbar2
    m_win->clear_border();
    m_win->end();
  } // Fl_Window* m_win
  parent_win = hwnd;
}

void Progress_Bar::show() {
  parent_win->deactivate();
  m_win->show();
  Fl::check();
}

void Progress_Bar::hide() {
  m_win->hide();
  parent_win->activate();
  Fl::check();
}
