// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef ui_h
#define ui_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_File_Browser.H>
#include <FL/Fl_Light_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
#include <FL/Fl_Button.H>

class AFSToolsUI {
public:
  AFSToolsUI();
  Fl_Double_Window *m_window;
  Fl_Choice *mode_sel;
  static Fl_Menu_Item menu_mode_sel[];
  static Fl_Menu_Item *btn_unpack;
  static Fl_Menu_Item *btn_pack;
  Fl_File_Browser *fbrowser1;
  Fl_Light_Button *btn_all_files;
  Fl_Round_Button *rb_ff;
  Fl_Round_Button *rb_fl;
  Fl_Round_Button *rb_nn;
  Fl_Button *run_btn;
};
extern void cb_fb(Fl_File_Browser*, void*);
#include <FL/Fl_Return_Button.H>
extern void cb_select_btn(Fl_Return_Button*, void*);
extern void cb_cancel_btn(Fl_Button*, void*);

class OF_Choiser {
public:
  OF_Choiser(Fl_Double_Window *hwnd, const char* path, const char* filter);
  Fl_Double_Window *m_win;
  Fl_File_Browser *fb;
  Fl_Return_Button *sel_btn;
  void show();
  int visible();
  char* value();
  Fl_Double_Window *parent_win; 
  char* filename; 
};
void cb_cancel_btn(Fl_Button* b, void* d);
extern OF_Choiser *fc;
void cb_select_btn(Fl_Return_Button* b, void* d);
void cb_fb(Fl_File_Browser *fb, void* userdata);
#include <FL/Fl_Window.H>
#include <FL/Fl_Progress.H>

class Progress_Bar {
public:
  Progress_Bar(Fl_Double_Window *hwnd);
  Fl_Window *m_win;
  Fl_Progress *w_pbar1;
  Fl_Progress *w_pbar2;
  Fl_Double_Window *parent_win; 
  void show();
  void hide();
};
#endif
